services:
  ghost:
    build: .
    container_name: ghost
    restart: always
    ports:
      - "${GHOST_PORT}:2368"
    depends_on:
      db:
        condition: service_healthy
    environment:
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASS}
      database__connection__database: ${DB_DB}
      mail__transport: ${MAIL_TRANSPORT}
      mail__from: ${SMTP_FROM}
      mail__options__host: ${SMTP_HOST}
      mail__options__name: ${SMTP_HOST}
      mail__options__port: ${SMTP_PORT:-587}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASSWORD}
    volumes:
      - ./content:/var/lib/ghost/content
    command: ["node", "current/index.js"]

  db:
    image: mysql:9.4@sha256:082063dca94535c76b91c6ef9b9f6748810e546887af5e8574a8cfa11eace184
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DB}
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 15