name: Docker Image TQ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@418e4b98bf2841bd337d0b24fe63cb36dc8afa55
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/ghost-docker
    
    - name: Push it - Latest
      uses: docker/build-push-action@v6.17.0
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_USERNAME }}/ghost-docker:latest
